name: Build and Deploy

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Git config
        run: |
          git config --global user.email "realacessoriosdev@gmail.com"
          git config --global user.name "realacessorios-dev"

      - name: Bump Version
        run: |
          npm version patch

      - name: Pull and Push changes to repository
        run: |
          git pull origin production --ff-only
          git push origin HEAD
          git push origin HEAD --tags

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run buildGit

      - name: Zip files
        run: |
          cp package.json ./ui-siap
          zip -r ./ui-siap.zip ./ui-siap

      - name: Deploy to Server60
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_60_HOST }}
          username: ${{ secrets.SERVER_60_USER }}
          key: ${{ secrets.SERVER_60_PASSWORD }}
          port: ${{ secrets.SERVER_60_PORT }}
          script: |
            scp ui-siap.zip ${{ secrets.SERVER_DESTINATION_PATH }}
            ssh ${{ secrets.SERVER_60_USER }}@${{ secrets.SERVER_60_HOST }} -p ${{ secrets.SERVER_60_PORT }} "cd ${{ secrets.SERVER_60_DESTINATION_PATH }}"
