name: Build and Deploy

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Git config
        run: |
          git config --global user.email "realacessoriosdev@gmail.com"
          git config --global user.name "realacessorios-dev"

      - name: Bump Version
        run: |
          npm version patch

      - name: Push changes to repository
        run: |
          git push origin HEAD --force
          git push origin HEAD --tags --force

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run buildGit

      - name: Zip files
        run: |
          cp package.json $GITHUB_WORKSPACE/ui-siap
          zip -r $GITHUB_WORKSPACE/ui-siap.zip $GITHUB_WORKSPACE/ui-siap
          chmod 644 $GITHUB_WORKSPACE/ui-siap.zip
        working-directory: ${{ github.workspace }}

      - name: Debug da existência de 'ui-siap.zip'
        run: |
          ls -al $GITHUB_WORKSPACE

      # - name: Deploy to Server60
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_60_HOST }}
      #     username: ${{ secrets.SERVER_60_USER }}
      #     key: ${{ secrets.SERVER_60_PRIVATE_KEY }}
      #     port: ${{ secrets.SERVER_60_PORT }}
      #     script: |
      #       scp $GITHUB_WORKSPACE/ui-siap.zip ${{ secrets.SERVER_60_DESTINATION_PATH }}
      #       ssh ${{ secrets.SERVER_60_USER }}@${{ secrets.SERVER_60_HOST }} -p ${{ secrets.SERVER_60_PORT }} "cd ${{ secrets.SERVER_60_DESTINATION_PATH }}"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_60_PRIVATE_KEY }}

      - name: Copy File to Server
        run: scp -P ${{ secrets.SERVER_60_PORT }} $GITHUB_WORKSPACE/ui-siap.zip ${{ secrets.SERVER_60_USER }}@${{ secrets.SERVER_60_HOST }}:${{ secrets.SERVER_60_DESTINATION_PATH }}
